global:
  resolve_timeout: 1m
  slack_api_url: 'https://hooks.slack.com/services/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'

route:
  receiver: 'slack-notifications'

receivers:
- name: 'slack-notifications'
  slack_configs:
  - channel: '#monitoring-alerts'
    send_resolved: true